<a href="https://colab.research.google.com/github/samvillasmith/EDA/blob/main/feature_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [4]:
df = pd.read_csv('/content/churn_modeling_v2.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           8969 non-null   object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.drop(columns = ["CustomerId", "RowNumber", "Surname"], axis=1, inplace=True)

In [7]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
df.Gender.value_counts()

Gender
Male      4864
Female    4105
Name: count, dtype: int64

In [9]:
df.Gender.mode()

0    Male
Name: Gender, dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           8969 non-null   object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [11]:
df['Gender'] = df['Gender'].fillna('Male')

In [12]:
df.Gender.value_counts()

Gender
Male      5895
Female    4105
Name: count, dtype: int64

## Label encoding

In [13]:
le = preprocessing.LabelEncoder()
df['Gender_label'] = le.fit_transform(df.Gender.values)

In [14]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0

In [15]:
df.Gender_label.value_counts()

Gender_label
1    5895
0    4105
Name: count, dtype: int64

## One Hot Encoding

In [17]:
one_hot = pd.get_dummies(df['Geography'])

In [18]:
one_hot

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [19]:
df_dummmies_de = pd.get_dummies(df, drop_first='True')

In [21]:
df_dummmies_de.head(5)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,0,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,0,False,True,False

## Target Encoding

Target encoding is a technique where you replace a categorical feature value with the mean of the target variable for that category. Here are some of its benefits and limitations:

Benefits:

Captures non-linear relationships: Unlike one-hot encoding, target encoding can capture non-linear relationships between the categorical feature and the target variable.
Reduces dimensionality: It creates a single numerical feature for each categorical feature, which is especially beneficial for high-cardinality categorical variables, where one-hot encoding would create a large number of new features.
Can improve model performance: In some cases, target encoding can lead to improved performance for models that struggle with high-dimensional sparse data or non-linear relationships.
Limitations:

Prone to overfitting: Target encoding can be susceptible to overfitting, especially on small datasets or when a category has very few instances. The encoded value for a category might be heavily influenced by a small number of data points.
Data leakage: If not implemented carefully, target encoding can lead to data leakage. This occurs when information from the target variable is used to create features for the training data, which can artificially inflate model performance on the training set and lead to poor generalization on unseen data. Techniques like cross-validation or adding smoothing can help mitigate this.
Sensitive to target distribution: The effectiveness of target encoding depends on the distribution of the target variable within each category. If the target distribution is very similar across categories, target encoding might not provide much benefit.
Not suitable for all models: Some models, like tree-based models, can handle categorical features directly and may not benefit significantly from target encoding.
It's important to use target encoding cautiously and consider techniques like smoothing or cross-validation to prevent overfitting and data leakage.

In [23]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.8.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.8.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 2.4 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.8.1

In [24]:
from category_encoders import TargetEncoder

In [25]:
encoder = TargetEncoder()

df1 = pd.read_csv('/content/churn_modeling_v2.csv')
df1.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [26]:
df1.drop(columns = ["CustomerId", "RowNumber", "Surname"], axis=1, inplace=True)

In [27]:
df1['Gender'] = df1['Gender'].fillna('Male')

In [28]:
df1.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [29]:
df['Gender Encoded'] = encoder.fit_transform(df1['Gender'], df1['Exited'])

In [30]:
df.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Gender Encoded
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0,0.250183
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0,0.250183
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0,0.250183
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,0.250183
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,0.250183

In [31]:
df['Gender Encoded'].value_counts()

Gender Encoded
0.171332    5895
0.250183    4105
Name: count, dtype: int64

## Hash Encoding

Hash encoding is a technique used to convert categorical features into numerical features. It works by applying a hash function to the categorical value and using the resulting hash as an index into a fixed-size vector. The corresponding element in the vector is then incremented or set to a specific value, depending on the implementation.

Here's a breakdown of the process and some key aspects:

How it works:

Hashing: A hash function takes a categorical value (like a word or string) and converts it into a fixed-size numerical value (the hash). The same input will always produce the same hash.
Indexing: The hash is used as an index into a pre-defined-sized array or vector.
Encoding: The value at that index is modified. This could be as simple as setting a 1 at that index if the category is present, or it could involve more complex weighting schemes.
Benefits:

Handles high cardinality: Hash encoding is particularly useful for categorical features with a very large number of unique values (high cardinality) because it avoids creating a huge number of new columns like one-hot encoding would.
Reduces memory usage: By using a fixed-size vector, it keeps the dimensionality of the data manageable, which can save memory.
Avoids explicit mapping: Unlike other encoding methods that require building a mapping between categories and numbers, hash encoding does this implicitly through the hash function.
Limitations:

Collisions: Different categorical values can sometimes produce the same hash. This is called a hash collision. Collisions can lead to some loss of information as multiple categories are mapped to the same index. The severity of collisions depends on the hash function and the size of the output vector.
Irreversibility: Once a category is hash-encoded, it's generally not possible to reverse the process and recover the original categorical value.
Lack of interpretability: The resulting numerical features don't have a direct, easily interpretable meaning in terms of the original categories.
No ordering preserved: Like one-hot encoding, hash encoding doesn't inherently preserve any order or relationship between categories.
Hash encoding is a good option when you have high-cardinality categorical features and memory or dimensionality is a concern, but you need to be aware of the potential for collisions and the loss of interpretability.

In [37]:
from category_encoders import HashingEncoder

In [38]:
X = df.Gender
y = df.Exited

In [43]:
ce_hash = HashingEncoder(cols=['Gender'])
ce_hash.fit_transform(X, y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      0      0      0      0      0      0      1
1         0      0      0      0      0      0      0      1
2         0      0      0      0      0      0      0      1
3         0      0      0      0      0      0      0      1
4         0      0      0      0      0      0      0      1
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      0      0      0      0      1      0      0
9996      0      0      0      0      0      1      0      0
9997      0      0      0      0      0      0      0      1
9998      0      0      0      0      0      1      0      0
9999      0      0      0      0      0      0      0      1

[10000 rows x 8 columns]

In [47]:
X = df.Geography

In [49]:
ce_hash2 = HashingEncoder(n_components=16, cols=['Geography'])
ce_hash2.fit_transform(X, y)

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9996,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9997,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9999,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0